name: 部署前端到GitHub Pages
on:
  push:
    branches: [xianyu-vue]  # 前端分支名
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      
      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # 对应你的Node版本
      
      - name: 安装依赖并打包
        run: |
          yarn install
          yarn build
      
      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 打包后的文件夹